### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by ifei17-hfut** [3d-motion-magnification/3d-motion-magnification.github.io#1]
Very interesting work! Please tell me when the full code will be available for us to learn!

**Comment by brandonyfeng** [comment]
Thanks for your interest @Jiafei127  - the code can be found [here](https://github.com/3d-motion-magnification/3d-motion-mag).

**Comment by ifei17-hfut** [comment]
Is it possible to publish the original "fork_1", "fork_2" and "standing" videos (not magnified) from the project homepage?

**Comment by brandonyfeng** [comment]
@Jiafei127 They are now included in the shared drive, and the [code](https://github.com/3d-motion-magnification/3d-motion-mag#handheld--tripod-video-captures) has been updated to handle this type of captures (partly using a tripod).
